### ISSUE TITLE
Enabling/Disabling Side Drawers (one at a time)

### ISSUE THREAD

**Issue by edulpn** [mutualmobile/MMDrawerController#102]
Hi!

I've been trying, for some days now, to disable one of the drawers. The context is: In my login screen I wanted that only my left drawer would be enabled (which is my "main menu") as long as the right one doesn't make sense on a login screen (the rightDrawerViewController is only a search tool for my app). I already tried to set setOpenDrawerGestureModeMask to MMOpenDrawerGestureModeNone as told on #87 , but this would disable both left and right drawers.
Also tried to customize the gesture behaviour setting MMOpenDrawerGestureMode to MMOpenDrawerGestureModeCustom, but I can't determine the gesture direction inside the setGestureShouldRecognizeTouchBlock.
Is there anything else I could try?

Thanks in advance,
Eduardo.

**Comment by yestay90** [comment]
Ok, thanks for help. I turned off drawer. However, I also want to remove nav controller from login controller. Is that possible?

**Comment by yestay90** [comment]
I used leftViewController and centerviewcontroller directly:centerContainer = MMDrawerController(centerViewController: centerSideNav, leftDrawerViewController: leftSideNav)
Now, I dont have Nav Bar. SO , how can I put nav bar again on the after authentication?

**Comment by thihaaung6245** [comment]
I cant do that in Swift,i mean disabling the left drawer in while i was at detail view.Any Help?Please?
