### ISSUE TITLE
How to use MMDrawerController with Storyboard?

### ISSUE THREAD

**Issue by hdoria** [mutualmobile/MMDrawerController#114]
Hi,

How can i use MMDrawerController with Storyboard?

**Comment by AnthonyMDev** [comment]
@TomSwift Is there any tutorial out there on how to use MMDrawerController with a storyboard using this category?

**Comment by TomSwift** [comment]
No "tutorial", but a sample project:  https://github.com/TomSwift/MMDrawerController-Storyboard/tree/master/KitchenSinkStoryboard
