### ISSUE TITLE
viewWillAppear on CenterViewController

### ISSUE THREAD

**Issue by Urkman** [mutualmobile/MMDrawerController#182]
Hello,

viewWillAppear is not called on CenterViewController after drawer is closed.
How can I detect, when the CenterViewController is active again after closing a drawer.

Thanks,
Urkman

**Comment by helmiS** [comment]
Hello, 

I need to refresh the center view after trigging some actions from the drawer but i can't do it since the view will appear isn't called. isn't there any solution for that?

**Comment by tommyle** [comment]
You can set a gesture completion block that calls viewWillAppear on the top view controller

```
    [_drawerController setGestureCompletionBlock:^(MMDrawerController *controller, UIGestureRecognizer *gesture) {
        if (self.navigationController.viewControllers.count > 0) {
            [self.navigationCntroller.viewControllers.lastObject viewWillAppear:true];
        }
    }];
```
