### ISSUE TITLE
UITableView in centerview can't be edited

### ISSUE THREAD

**Issue by mengxy** [mutualmobile/MMDrawerController#184]
I have an UITableView in centerview. While the tableview is set editing, I can't drag cells up and down.

**Comment by raybon-lee** [comment]
I hava a problem in left ViewController ,then I did select the row enter my centerView ,the centerVC is tabbarVC ,then push nextVc from CenterVC,and leftNavItem of  the nextVC  is not system back Item ,i look have the    effect of   DDMenuController ,now ,what i can do?
