### ISSUE TITLE
Is this possible to make sliding menu overlap center view controller instead of animate it to the right/left?

### ISSUE THREAD

**Issue by pzmudzinski** [mutualmobile/MMDrawerController#185]
Title explains everything :)

**Comment by akhilcb** [comment]
Anyone managed to do this? We are using "MMDrawerController" and it works great but we have a requirement that the right drawer should slide over the center view. Just wondering if anyone managed to do this by tweaking this library someway.

**Comment by iHamzaaK** [comment]
Any update on this?
