### ISSUE TITLE
CenterViewController reload problem

### ISSUE THREAD

**Issue by nottix** [mutualmobile/MMDrawerController#195]
I found a problem when switching between different CenterViewController. 
There are the steps:
1. Call setCenterViewController with ViewControllerA
2. Then call setCenterViewController with ViewControllerB
3. Then re-call setCenterViewController with ViewControllerA (same instance of 1) and the drawer recreate the view.

What can i do to show the same view (ViewControllerA) without recreating it everytime? (without using restoration state)

Thank you

**Comment by moonvader** [comment]
This method works well! Thank you!
