### ISSUE TITLE
Swipe to left delete is not working on UITableViewCell

### ISSUE THREAD

**Issue by ShreeshGarg** [mutualmobile/MMDrawerController#207]
I have tried in my project to enable swipe to delete functionality and found that some times it takes effect and most of the time not. 

by adding following code snippet in MMdrawercontroller.m I got this working : 
- (BOOL)gestureRecognizer:(UIGestureRecognizer *)gestureRecognizer shouldRecognizeSimultaneouslyWithGestureRecognizer:(UIGestureRecognizer *)otherGestureRecognizer
  {
  
  if([otherGestureRecognizer isKindOfClass:[UISwipeGestureRecognizer class]])
  {
      UISwipeGestureRecognizer *recog = (UISwipeGestureRecognizer *)otherGestureRecognizer;
      if(recog.direction == UISwipeGestureRecognizerDirectionLeft && [recog.view isKindOfClass:[UITableViewCell class]]) return NO;
  }
  
  return YES;

}

I am new to GitHub. So adding my suggestion here.

**Comment by jonasman** [comment]
Yes, I have a Left and Center, And swipe to delete makes sence!

**Comment by dorinsimina** [comment]
You can check in shouldReceiveTouch:

NSString *className = NSStringFromClass([touch.view class]);
    if ([className isEqualToString:@"UITableViewCellContentView"]) {
        return NO;
    }
