### ISSUE TITLE
Conflict: UIScrollView in CenterViewController

### ISSUE THREAD

**Issue by zhw511006** [mutualmobile/MMDrawerController#229]
I have a UIScrollView in CenterViewController and the scrollview has three pages.
When in first page, swipe to right, I hope to open the LeftViewController, how to deal with the conflict pan gesture, Thank you very much!

**Comment by JanHalozan** [comment]
No problem at all. In case you're wondering, the `panGestureRecognizer` is an ivar of the `MMDrawerController` class. I've just edited the `setupGestureRecognizers` method and stored a reference to the gesture recognizer. If you have any more questions feel free to ask.

```
- (BOOL)gestureRecognizer:(UIGestureRecognizer *)gestureRecognizer shouldRequireFailureOfGestureRecognizer:(UIGestureRecognizer *)otherGestureRecognizer
{
    if (gestureRecognizer != panGestureRecognizer || self.openSide != MMDrawerSideNone)
        return NO;

    const CGPoint velocity = [panGestureRecognizer velocityInView:gestureRecognizer.view];

    if (fabsf(velocity.y) > fabsf(velocity.x)) //If not a horizontal gesture return
        return NO;

    const CGPoint point = [gestureRecognizer locationInView:gestureRecognizer.view];

    if (([self isPointContainedWithinLeftBezelRect:point] && self.leftDrawerViewController) || ([self isPointContainedWithinRightBezelRect:point] && self.rightDrawerViewController))
    {
        if ([otherGestureRecognizer isKindOfClass:NSClassFromString(@"UIScrollViewPanGestureRecognizer")])
        {
            otherGestureRecognizer.enabled = NO;
            otherGestureRecognizer.enabled = YES;

            return YES;
        }
    }

    return NO;
}
```

**Comment by mingming1222** [comment]
@farfromrefug  Thank you very much !!!

**Comment by lipeiran** [comment]
hi,i find "CGPoint velocity = [self.panGesture velocityInView:self.panGesture.view];",velocity.x & y is always 0. anybody can help me? THX

**Comment by lipeiran** [comment]
@mingming1222,Please Help Me~

**Comment by 0x0078** [comment]
sorry...i dont no.  😂

发自我的 iPhone

**Comment by idoan** [comment]
"I've just edited the setupGestureRecognizers method and stored a reference to the gesture recognizer"

Just to clear the confusion to @JanHalozan 's great answer, just assign local variable  `pan` to `panGestureRecognizer` that you defined as a property in `setupGestureRecognizers` . 

You must also change `isPointContainedWithRightBezelRect` `isPointContainedWithinRightBezelRect` (change With to Within) to fix the error.

**Comment by idoan** [comment]
@farfromrefug is right. We must remove that last if condition for UIScrollViewPanGestureRecognizer, because when the transitionStyle is changed to pageCurl, this check doesn't work expectedly, since pageCurl calls UIPanGestureRecognizer .

**Comment by qpwang** [comment]
velocity.x & y is always 0.

  +1

**Comment by JanHalozan** [comment]
Is this already somewhere in the implementation or in a PR? Otherwise I'll submit a new pull request.
