### ISSUE TITLE
Pushing centerviewcontroller

### ISSUE THREAD

**Issue by mstzn** [mutualmobile/MMDrawerController#238]
Hi,
How can I push view controller on centerviewcontroller? And after pop?
I can't find any information in documentation.

**Comment by chlebta** [comment]
@mstzn  how do you solved it ?

**Comment by mstzn** [comment]
If you init MMDrawerController with NavigationController, you can push it.
Code example below.

self.navigationController = [[UINavigationController alloc] initWithRootViewController:self.someViewController];
        self.navigationController.navigationBarHidden = YES;
        self.drawerController = [[MMDrawerController alloc] initWithCenterViewController:self.navigationController leftDrawerViewController:self.menuViewController];

When you push something on center, just cast it to NavigationController and try push after cast.

**Comment by chlebta** [comment]
Sorry, but if I'm right this will dealloc the current centerView and put new viewController, embedded in navigation Controller, in the center view instead ? 

Can you check my issue over here : https://github.com/mutualmobile/MMDrawerController/issues/386

**Comment by mstzn** [comment]
The controllers running like UIViewController. So I just init MMDrawer with NavigationController on center. Than I push and pop viewControllers to my NavigationController. This working outside of MMDrawer.

Also MMDrawer not have current without init, so when you init it with navigationController, not firing any dealloc.

"initWithCenterViewController:(UIViewController *)centerViewController leftDrawerViewController:(UIViewController *)leftDrawerViewController"

**Comment by mstzn** [comment]
This is that section of my AppDelegate file:

```
- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions {

self.navigationController = [[UINavigationController alloc] initWithRootViewController:self.homeViewController];
        self.navigationController.navigationBarHidden = YES;
        self.drawerController = [[MMDrawerController alloc] initWithCenterViewController:self.navigationController leftDrawerViewController:self.leftMenuViewController];

        [self.drawerController setShowsShadow:YES];
        [self.drawerController setRestorationIdentifier:@"MMDrawer"];
        self.drawerController.shouldStretchDrawer = NO;
        [self.drawerController setMaximumLeftDrawerWidth:320.0f-44.0f];
        [self.drawerController setOpenDrawerGestureModeMask:MMOpenDrawerGestureModeAll];
        [self.drawerController setCloseDrawerGestureModeMask:MMCloseDrawerGestureModeAll];
        //[self.drawerController setDrawerVisualStateBlock:[MMDrawerVisualState parallaxVisualStateBlockWithParallaxFactor:2.0f]];
        [self.drawerController setDrawerVisualStateBlock:[MMDrawerVisualState swingingDoorVisualStateBlock]];
        //[self.drawerController setDrawerVisualStateBlock:[MMDrawerVisualState slideAndScaleVisualStateBlock]];
        //[self.drawerController setDrawerVisualStateBlock:[MMDrawerVisualState slideVisualStateBlock]];

        self.window.rootViewController = self.drawerController;

```
