### ISSUE TITLE
[Question] Navigation between ViewControllers (Master/Detail)

### ISSUE THREAD

**Issue by joselufo** [mutualmobile/MMDrawerController#249]
Hi!

I'm trying to implement a "Master / Detail" with a "Navigation drawer" but I'm not getting. 

```
                               ---mm_left---[NavigationController]---root---[LeftViewController]:3 items---push--- to [ViewController2] below
           [MMDrawerController]---mm_center---[NavigationController]---root---[HomeController]---push---[ViewController1]---push---[ViewController2]
                               ---mm_right---.....
```

The problem I have is that when from the "HomeViewController" change to another "ViewController" I still can open the "Navigation Drawer" and I'm not interested. What I want is that when the Detail can not open the "NavigationDrawer" only when press back and then the "HomeViewController".

Attached image "StoryBoard":

![screen shot 2014-05-15 at 17 15 31](https://cloud.githubusercontent.com/assets/3983619/2986363/c97cfaf0-dc43-11e3-8f6d-3740fd2860a1.png)

I leave the link to the example I have done.  https://github.com/joselufo/MMDrawerControllerDemo

**Comment by kaandedeoglu** [comment]
Just as a note - the gist works perfectly for most cases, but fails when an interactive gesture is started and then canceled. The solution is to become the is to conform to UINavigationControllerDelegate and replace popViewController with the -(void)navigationController:(UINavigationController *)navigationController didShowViewController:(UIViewController *)viewController animated:(BOOL)animated.
