### ISSUE TITLE
Dragging to Open Left View shows Black Line

### ISSUE THREAD

**Issue by jeffreyjackson** [mutualmobile/MMDrawerController#254]
I have both the center and left views set with a background color white.  When dragging to open the left view there is a very thin black line that flashes as you drag the view.  
![ios simulator screen shot may 24 2014 12 34 56](https://cloud.githubusercontent.com/assets/867999/3075052/7e546a98-e361-11e3-9685-632a5ee1b5b2.png)

**Comment by hemang-azilen** [comment]
This bug ever solved? My app's background is black and its showing white line.

**Comment by jeffreyjackson** [comment]
I'm not sure if it was solved, but I ended up added a subview with a white background that extended past the width of the main view.  Since the main view clipped the subview the black line was never shown.

**Comment by skgwazap** [comment]
There is method 
`panGestureCallback:(UIPanGestureRecognizer *)panGesture` 
in MMDrawerController.m
In case of UIGestureRecognizerStateChanged line 
`[panGesture translationInView:self.centerContainerView];` 
returns values like 9.000 and 9.500 (delta is 0.5).
This delta causes wrong _newFrame_ calculation for _centerContainerView_ 
`[self.centerContainerView setCenter:CGPointMake(CGRectGetMidX(newFrame), CGRectGetMidY(newFrame))];`

Rounding, ceiling or flooring the returned value does the job. I did it in`-(CGFloat)roundedOriginXForDrawerConstriants:(CGFloat)originX`

```
-(CGFloat)roundedOriginXForDrawerConstriants:(CGFloat)originX{
    ...
    // No changes
    ...
    return ceil(originX);
}
```
