### ISSUE TITLE
mm_visibleDrawerFrame: unrecognized selector 

### ISSUE THREAD

**Issue by pareshmasani** [mutualmobile/MMDrawerController#281]
I am using this library using cocoapods. I get following exception, can someone please help me to resolve it? 

```
-[MenuViewController mm_visibleDrawerFrame]: unrecognized selector sent to instance 0xb01f150
```

I have uploaded sample project to show the way I am using this pod - https://dl.dropboxusercontent.com/u/72253873/PodTest.zip. Open PodTest workspace and If you run PodExampleProject you will get above exception.

**Comment by Edig** [comment]
Sorry for to much time ago, where do you add "-all_load"?
