### ISSUE TITLE
Some time UIPanGestureRecognizer become enable = no for pan Gesture when we frequently open and close drawer

### ISSUE THREAD

**Issue by patelparthc** [mutualmobile/MMDrawerController#290]
i was facing same issue like .https://github.com/mutualmobile/MMDrawerController/issues/284  but than i updated with new source and found that black screen issue is solved but after so many open close drawer animation some time mmdrawercontroller stope panning.. i debug and observe couple of things than found that in some case default pan remain enable = no for forever.. 

When panning was working:-
UIPanGestureRecognizer: 0x14ef9e10; state = Possible; view = <UIView 0x14ef9740>; target= (action=panGestureCallback:, target=<MMDrawerController 0x14ef88d0>)

When panning was stopped working:-
 UIPanGestureRecognizer: 0x14ef9e10; state = Possible; enabled = NO; view = <UIView 0x14ef9740>; target= <(action=panGestureCallback:, target=<MMDrawerController 0x14ef88d0>)

Right now i have make property of UIPanGestureRecognizer of mmdrawercontroller and checked on viewwillapper and if its not enable than make it manually enable = yes.

May this trouble me some where later on or not ?

**Comment by guillaumealgis** [comment]
Still an issue. Just replicated it myself multiple times.

The pan gesture is disabled [here](https://github.com/mutualmobile/MMDrawerController/blob/master/MMDrawerController/MMDrawerController.m#L1058) and never re-enabled later.
