### ISSUE TITLE
Cocoapods duplicate file in build phase

### ISSUE THREAD

**Issue by simonmcl** [mutualmobile/MMDrawerController#295]
Not a major issue just a little annoying. Every time I update our pods I get a warning in Xcode 6 to say that the pod MMDrawerController's build phase contains a duplicate file for MMDrawerController+subclass.h. Would be great if it could be removed

**Comment by ryanmaxwell** [comment]
yeah this is annoying +1

**Comment by eytanbiala** [comment]
See #306
