### ISSUE TITLE
Feature request: Resize Center View

### ISSUE THREAD

**Issue by kenthinson** [mutualmobile/MMDrawerController#307]
Hello I was wondering if it would be possible to have a feature added where the center view would resize instead of moving off to the side. Trying to make a iPad app like the YouTube app. Where when you rotate to landscape the drawer controller locks open and the right pane shows the whole view. But when in portrait the drawer acts like normal.

**Comment by kcharwood** [comment]
That's a good idea, but currently not supported. Would be a good 2.0 feature if we get around to it. Closing for now, but marking with the appropriate label for future follow up.
