### ISSUE TITLE
Push new view controller from drawer.

### ISSUE THREAD

**Issue by 128keaton** [mutualmobile/MMDrawerController#320]
Hi guys, I finally got a working implementation in my application, now I want to mess it up again. I'd like to switch views with my drawer. How can I accomplish this?

**Comment by AnthonyMDev** [comment]
If I'm understanding this correctly, you're trying to switch the `centerViewController` programmatically from you `leftViewController`?

Just import the `UIViewController+MMDrawerController` category. Then:

```
UIViewController *newCenterViewController = [UIViewController alloc] init];
[self.mm_drawerController setCenterViewController:newCenterViewController];

// If you want to then close the sideViewController as well.
[self.mm_drawerController toggleDrawerSide:MMDrawerSideNone animated:YES completion:nil];
```

**Comment by 128keaton** [comment]
@AnthonyMDev thank man, I eventually got it.
