### ISSUE TITLE
Push another MMdrawerController from an existing MMdrawerController

### ISSUE THREAD

**Issue by satyamkrishna** [mutualmobile/MMDrawerController#321]
Hi , I am using trying to push a MMdrawer type controller from an exisitng controller which also is the mmdrawer type. The Problem I am facing is that i am not able to set title or title view for the second view.

**Comment by kcharwood** [comment]
Could you post an example and reopen this issue?

I'm also curious to understand the UX behind this decision, and if that is indeed a valid use case.

**Comment by satyamkrishna** [comment]
So my use case is that i have an app that has a navigation drawer on the first page for which i use this. Then from this screen i open a list of items on which i need to apply an filter. So i thought i will use that again so that user can switch easily between different filters. 

On first screen i thought i will use a left drawer and on the second a right.
