### ISSUE TITLE
MMDrawerController vs DZNEmptyDataSet

### ISSUE THREAD

**Issue by mariohahn** [mutualmobile/MMDrawerController#322]
If i use DZNEmptyDataSet and MMDrawerController in one Project the gesture recognizer  takes over every touch. Its much too easy to open the menu. 

I only integrated  DZNEmptyDataSet with Pods haven't implemented it in the Code yet, nevertheless i am fighting with such odd behaviours.

**Comment by kcharwood** [comment]
I'm not familiar with that project. Can you post an example and reopen this issue?
