### ISSUE TITLE
Fixed center view

### ISSUE THREAD

**Issue by danielgomezrico** [mutualmobile/MMDrawerController#330]
I can adjust the drawer animation but not the center view animation, how can I do it? I need to let the center view fixed and show the right/left drawer on top of it.

**Comment by kcharwood** [comment]
This is currently something still listed in the ["What this doesn't do"](https://github.com/mutualmobile/MMDrawerController#what-this-library-doesnt-do) section.

The complexities to support that proved to be to difficult originally if we wanted to keep the code base sane.

If we ever get around to a DrawerController 2.0, this would be a great feature.

**Comment by danielgomezrico** [comment]
Ok, thanks ;)
