### ISSUE TITLE
Drawer not openning when center view is a UISplitViewController (Portrait only)

### ISSUE THREAD

**Issue by paulwcy** [mutualmobile/MMDrawerController#332]
Drawer does not open when the center view is a UISplitViewController. (iPad, portrait mode)

Works fine when rotated to landscape.

**Comment by paulwcy** [comment]
Found a workaround (applicable only for iPad, portrait mode).

```
MMDrawerController *mm_drawerController = (MMDrawerController *)self.splitViewController.parentViewController;
[mm_drawerController toggleDrawerSide:MMDrawerSideLeft animated:YES completion:nil];
```

**Comment by kcharwood** [comment]
`self.splitViewController.mm_drawerController` should also be the same reference there.
