### ISSUE TITLE
Is there a simple example available?

### ISSUE THREAD

**Issue by jdutchak** [mutualmobile/MMDrawerController#334]
Hello
Do you have a simple example. I am creating a single view application and I want a left drawer that will contain a uitableview.

**Comment by daxh** [comment]
Hi, recently I've faced with some problems and decided to create simple project to demonsrate how to work with MMDC in different ways. Here comes the link

https://github.com/daxh/MMDrawerController-issue-searchbar

**Comment by kcharwood** [comment]
Curious - Do you see the kitchen sink example included in the repo as too complicated?

**Comment by jdutchak** [comment]
Yes I did I got it working thanks !Sent from Yahoo Mail for iPhoneAt Mar 10, 2015, 9:24:19 AM, Kevin Harwood wrote:Curious - Do you see the kitchen sink example included in the repo as too complicated?
