### ISSUE TITLE
Table View not working in Left View Controller

### ISSUE THREAD

**Issue by keithyeohh** [mutualmobile/MMDrawerController#336]
Hey there, really thank you so much for the hard effort by label this great source code openly.

My left panel contains 1 table view. The first time when I open up left panel and tap on one cell, it does trigger didSelectRowAtIndexPath function. But again, after I tried to tap on the next time I open up the left panel, it doesn't work at all.

Seems like something blocking on top of the table view.

First time open panel I got the logs of the view's subviews

    2015-02-20 09:13:09.219 Bleepp[3431:613] self.view subviews (
        <UITableView: 0x7ff333848a00; frame = (0 0; 100 568); clipsToBounds = YES; autoresize = RM+BM; gestureRecognizers = <NSArray: 0x7ff33245fb50>; layer = <CALayer: 0x7ff33245cad0>; contentOffset: {0, 0}>,
        <_UILayoutGuide: 0x7ff332448960; frame = (0 0; 0 20); hidden = YES; layer = <CALayer: 0x7ff332448a30>>,
        <_UILayoutGuide: 0x7ff3326a19a0; frame = (0 568; 0 0); hidden = YES; layer = <CALayer: 0x7ff3326b5470>>
    )

Second time open

    2015-02-20 09:13:16.026 Bleepp[3431:613] self.view subviews (
        <UITableView: 0x7ff333848a00; frame = (0 0; 100 568); clipsToBounds = YES; autoresize = RM+BM; gestureRecognizers = <NSArray: 0x7ff33245fb50>; layer = <CALayer: 0x7ff33245cad0>; contentOffset: {0, 0}>,
        <_UILayoutGuide: 0x7ff332448960; frame = (0 0; 0 20); hidden = YES; layer = <CALayer: 0x7ff332448a30>",
        <_UILayoutGuide: 0x7ff3326a19a0; frame = (0 568; 0 0); hidden = YES; layer = <CALayer: 0x7ff3326b5470>>,
        <UIView: 0x7ff332488d50; frame = (0 0; 100 568); autoresize = W+H; layer = <CALayer: 0x7ff332488e10>>
    )

I realize second time when I open the subviews added an extra view there. I suspect the view is blocking the tableview.

Can you please advise what approach should I do to make it works? Thanks!

*Note: I've try to log in didSelectRowAtIndexPath: and the UIView added right after I tap on the cell.

    - (void)tableView:(UITableView *)tableView didSelectRowAtIndexPath:(NSIndexPath *)indexPath
    {
        NSLog(@"before self.view subviews %@", self.view.subviews);
    
        UIStoryboard *storyboard        = [UIStoryboard storyboardWithName:@"Main" bundle:nil];
        MMNavigationController *nc      = (MMNavigationController *)[storyboard instantiateViewControllerWithIdentifier:@"SettingsNC"];

        __weak typeof(self) wSelf = self;
        [self.mm_drawerController setCenterViewController:nc withCloseAnimation:YES completion:^(BOOL finished) {

            NSLog(@"self.view subviews %@", wSelf.view.subviews);
        }];
    
        [tableView selectRowAtIndexPath:indexPath animated:NO scrollPosition:UITableViewScrollPositionNone];
        [tableView deselectRowAtIndexPath:indexPath animated:YES];
    }

**Comment by keithyeohh** [comment]
This is my workaround and I am not so sure whether is the correct approach.

    - (void)viewWillAppear:(BOOL)animated
    {
        [super viewWillAppear:animated];
    
        [self.view bringSubviewToFront:self.mTableView];
    }

I always bring the table view to front whenever the view appear.

**Comment by kcharwood** [comment]
The KitchenSink example uses table views inside the drawers. I suspect something in your view hierarchy is causing the issue.
