### ISSUE TITLE
Method if the left or right drawer is visible?

### ISSUE THREAD

**Issue by AldoOS** [mutualmobile/MMDrawerController#337]
How can i know if the left or right drawer is visible in the screen.

**Comment by eytanbiala** [comment]
This should work for you:

`````
-(BOOL)isLeftOpen
{
    return (self.mm_drawerController.openSide == MMDrawerSideLeft);
}

-(BOOL)isRightOpen
{
    return (self.mm_drawerController.openSide == MMDrawerSideRight);
}

`````
You can also just return the open side, and use that in your code if needed:

`````
-(MMDrawerSide)openSide
{
     return (self.mm_drawerController.openSide;
}
`````

**Comment by AldoOS** [comment]
Thank you, i didn't test it yet. How about notification when the CenterViewController Appear?

**Comment by eytanbiala** [comment]
Use `-(void)viewWillAppear:(BOOL)animated` in each of your drawer view controllers.

**Comment by AldoOS** [comment]
Hi eytanbiala, it doesn't work for The center view controllers, it work just for left and right drawer.

**Comment by eytanbiala** [comment]
Sorry I misread, thought you wanted to know when the drawer VC appears. To be notified when your center view controller appears, you can post a notification from `-(void)viewDidDisappear:(BOOL)animated` in your drawer view controllers. If you are programmatically closing the drawer, there is `closeDrawerAnimated:YES completion:^{ // your code here}`

**Comment by AldoOS** [comment]
It can work too and i'm using this technique, but in my project i need to know every time the center view controller is presented to update the navigation barbutton items. Anyway i will try to put some code and post some notification from MMDrawerController class. Thank you

**Comment by kcharwood** [comment]
If you are programmatically closing the drawer, the completion blocks would help.

If the user is closing it with a gesture, you can use `setGestureCompletionBlock:` to get a callback when that gesture is complete, and you can determine the new state of the drawer.
