### ISSUE TITLE
myCustomSubview is?

### ISSUE THREAD

**Issue by chivaszhu** [mutualmobile/MMDrawerController#344]
[self.drawerController.centerViewController myCustomSubview];  
how myCustomSubview?

**Comment by kcharwood** [comment]
I'm not sure I am following the question?

**Comment by chivaszhu** [comment]
I want to use MMDrawerController in my project。In my home page has a scrollview and two tableview in scrollview.so left slide and right slide MMDrawerController not work.please help me .I saw [self.drawerController.centerViewController myCustomSubview] is solve this problem？I don't know myCustomSubview what this is?
