### ISSUE TITLE
New Release?

### ISSUE THREAD

**Issue by dcosson** [mutualmobile/MMDrawerController#353]
Hey, it looks like there've been 19 commits since the last release in August with a bunch of bugfixes.  Is there a timeframe for the next cocoapods release?  Thanks.

**Comment by SpacyRicochet** [comment]
Seconded. I'm currently resorting to forking the project to get the new changes, instead of relying on the pod spec. A next CocoaPods release would be appreciated.

**Comment by kcharwood** [comment]
I'm hoping to push an update sometime this week.

**Comment by kcharwood** [comment]
Just pushed 0.6.0

**Comment by SpacyRicochet** [comment]
Great, thanks!
