### ISSUE TITLE
Darken center view controller when drawer side view appears

### ISSUE THREAD

**Issue by stefanocdn** [mutualmobile/MMDrawerController#354]
Hi, I m trying to darken the center view controller when side drawer appears, in method

      self.drawerController setDrawerVisualStateBlock:^(MMDrawerController *drawerController, MMDrawerSide drawerSide, CGFloat percentVisible) 

But setting alpha of center view controller to 0.7 does not work with the animation.

Any idea how to accomplish this?

**Comment by kcharwood** [comment]
This should work.

I just dropped this line in the parallax visual state block in the example and it works fine

`drawerController.centerViewController.view.alpha = 1.0-percentVisible;`
