### ISSUE TITLE
Implicit conversion loses floating-point precision: 'double' to 'CGFloat'

### ISSUE THREAD

**Issue by jakeatwork** [mutualmobile/MMDrawerController#425]
Using MMDrawerController with Swift 2 in Xcode 7 I hit the error above when I go to build the archive. On lines like the following in MMDrawerVisualState.m (for example):

```
CGFloat minScale = .90;
CGFloat scale = minScale + (percentVisible*(1.0-minScale));
```

Any ideas on how to fix?

**Comment by danmurrelljr** [comment]
Hi @jakeatwork, the 1.0 is probably your double. 

Try using that as a CGFloat instead, with CGFloat(1.0), and see if that quiets the warning.

**Comment by jakeatwork** [comment]
Thanks @danmurrelljr for the quick reply!

Well...that's one, but I'm getting 16 errors across two files. I have a pretty standard setup and I'm surprised nobody else has this issue (I've searched high and low for input on this error specific to your library - as well as to the issue in general). 

Like I said, I'm pretty new to swift and I have a fully functioning app...it works fine when I build locally, but when I got to build the archive, it fails due to these errors (they are not warnings).

Just to show you a few example - as it could be I have something else wrong if people are using your library in swift apps with a bridged header. Or if there's something I could do to supress these errors if the app seems to work fine on iPhone 4, 5, 5S, 6 and 6S (with iOS 7.0 and up).

![image](https://cloud.githubusercontent.com/assets/1273830/12182687/9d443892-b53e-11e5-91b4-302f4bd451f6.png)

![image](https://cloud.githubusercontent.com/assets/1273830/12182692/a6640326-b53e-11e5-8acf-40bb786755df.png)

![image](https://cloud.githubusercontent.com/assets/1273830/12182700/b178f5be-b53e-11e5-8925-bc4d55cee279.png)

**Comment by danmurrelljr** [comment]
Probably what is happening is your archive is writing for 64 bit architecture, and won't allow you to use mixed floats and doubles.

You could go through and convert all these numbers to CGFloat()s, or what might be easier is use this swift rewrite of MMDrawerController instead.

https://github.com/sascha/DrawerController

**Comment by jakeatwork** [comment]
ok...sounds good. thanks.
