### ISSUE TITLE
iOS7 crashes when setCenter

### ISSUE THREAD

**Issue by NSCabezon** [mutualmobile/MMDrawerController#428]
This issue is just iOS7 related, after a setCenter it crashes, the call is:

`[self.mm_drawerController setCenterViewController:controller];`

is a navigation controller btw ant the crash says:

`Objective: {objective 0x16590a00: <750:0.0910713, 251:889, 250:876> + <251:-1>*0x16528ea0.marker{id: 1353} + <750:1>*0x16547880.negError{id: 142} + <251:1>*0x16547880.posErrorMarker{id: 141} + <999:2>*0x16549f30.negError{id: 3} + <999:2>*0x1654a390.negError{id: 6} + <251:-1>*0x165521f0.marker{id: 1347} + <251:1>*0x1657a5a0.marker{id: 1424} + <251:1, 250:1>*0x1657e620.marker{id: 148} + <251:1>*0x1657fda0.marker{id: 1331} + <251:1>*0x1658a890.marker{id: 29} + <750:-1>*0x1658a8c0.marker{id: 31} + <250:1>*0x1658c260.marker{id: 10} + <250:-1>*0x1658c290.marker{id: 12} + <250:-1>*0x1658c2c0.marker{id: 14} + <250:-1>*0x1658c2f0.marker{id: 17} + <250:-1>*0x1658c320.marker{id: 20} + <251:-1>*0x1658c750.marker{id: 37} + <251:-1>*0x1658c780.marker{id: 41} + <251:-1>*0x1658ca30.marker{id: 56} + <251:-1>*0x1658ca90.marker{id: 60} + <250:-1>*0x1658cb50.marker{id: 68} + <250:-1>*0x1658cb80.marker{id: 70} + <999:2>*0x1658cd90.negError{id: 79} + <999:2>*0x1658cf70.negError{id: 82} + <251:-1, 250:-1>*0x1658d170.marker{id: 84} + <251:-1, 250:-1>*0x1658d200.marker{id: 92} + <750:1, 250:1>*0x16598a60.negError{id: 136} + <750:1, 250:1>*0x1659abe0.negError{id: 138} + <750:1, 251:1>*0x1659b610.negError{id: 140} + <251:1>*0x1659f9e0.marker{id: 209} + <251:1>*0x1659fdb0.marker{id: 211} + <251:-1>*0x165a1660.marker{id: 227} + <251:-1>*0x165a16c0.marker{id: 233} + <251:1>*0x165a4930.marker{id: 240} + <251:1>*0x165a4960.marker{id: 242} + <251:-1>*0x165a5270.marker{id: 258} + <251:-1>*0x165a52d0.marker{id: 264} + <251:-1>*0x165aa280.marker{id: 1378} + <750:1, 251:1>*0x165b55f0.negError{id: 362} + <750:1, 251:1>*0x165b5650.posErrorMarker{id: 363} + <251:1>*0x165c16f0.marker{id: 1329} + <251:-1>*0x165d0150.marker{id: 1446} + <251:-1>*0x165e9810.marker{id: 1384} + <251:2>*0x166062c0.marker{id: 1544} + <251:2>*0x16609780.marker{id: 1572} + <251:1>*0x1660cf20.marker{id: 1453} + <251:-1>*0x16616d20.marker{id: 1477} + <750:1, 251:1>*0x1661f620.negError{id: 1603} + <251:2>*0x16621250.marker{id: 1648} + <251:2>*0x1662ed50.marker{id: 1667} + <750:1, 251:1>*0x16657d60.negError{id: 272} + <750:1, 251:1>*0x16667670.negError{id: 1561} + <251:1>*0x16679c00.marker{id: 1455} + <251:2>*0x1667dee0.marker{id: 293} + <750:1, 251:1>*0x1667e810.negError{id: 1641} + <251:2>*0x1667f550.marker{id: 1534} + <251:2>*0x166815c0.marker{id: 283} + <750:1>*0x16683a30.negError{id: 278} + <251:1>*0x16683a30.posErrorMarker{id: 277} + <750:1, 251:1>*0x1669cf50.negError{id: 274} + <750:1, 251:1>*0x166c1020.negError{id: 1637} + <750:1, 251:1>*0x166c4050.negError{id: 276} + <251:2>*0x166c5460.marker{id: 303} + <750:1, 251:1>*0x166c58c0.negError{id: 311} + <750:1, 251:1>*0x166c5900.negError{id: 313} + <750:1, 251:1>*0x166c5ea0.negError{id: 315} + <750:1>*0x166c5ee0.negError{id: 317} + <251:1>*0x166c5ee0.posErrorMarker{id: 316} + <251:2>*0x166c6290.marker{id: 322} + <251:2>*0x166c6940.marker{id: 332} + <251:2>*0x166c6fd0.marker{id: 341} + <251:7>*0x166c7c00.marker{id: 350} + <750:1>*0x166d5b20.negError{id: 1491} + <251:1>*0x166d5b20.posErrorMarker{id: 1490} + <750:1, 251:1>*0x166e1910.negError{id: 1525} + <750:1, 251:1>*0x166e1b80.negError{id: 1599} + <251:2>*0x166e3000.marker{id: 1629} + <750:1>*0x166e6550.negError{id: 1643} + <251:1>*0x166e6550.posErrorMarker{id: 1642} + <750:1, 251:1>*0x166e7b50.negError{id: 1523} + <750:1>*0x166e7fb0.negError{id: 1529} + <251:1>*0x166e7fb0.posErrorMarker{id: 1528} + <251:2>*0x166ee1e0.marker{id: 1506} + <750:1, 251:1>*0x166f2ba0.negError{id: 1485} + <750:1, 251:1>*0x166f63c0.negError{id: 1639} + <251:2>*0x166f92b0.marker{id: 1591} + <750:1>*0x166fae60.negError{id: 1605} + <251:1>*0x166fae60.posErrorMarker{id: 1604} + <750:1, 251:1>*0x1674c460.negError{id: 1487} + <251:2>*0x167563e0.marker{id: 1553} + <251:2>*0x16758ec0.marker{id: 1496} + <251:2>*0x167599d0.marker{id: 1620} + <251:-1>*0x1676bb90.marker{id: 1471} + <750:1, 251:1>*0x1676d4f0.negError{id: 1565} + <251:2>*0x16771070.marker{id: 1582} + <750:1, 251:1>*0x1677a380.negError{id: 1489} + <750:1, 251:1>*0x1677bdc0.negError{id: 1527} + <750:1>*0x1677c6d0.negError{id: 1567} + <251:1>*0x1677c6d0.posErrorMarker{id: 1566} + <750:1, 251:1>*0x1677ce90.negError{id: 1601} + <251:2>*0x1677fa70.marker{id: 1610} + <750:1, 251:1>*0x1678c200.negError{id: 1563} + <251:2>*0x1679eca0.marker{id: 1658} + <251:2>*0x1679ecf0.marker{id: 1515} + <251:1>*0x17937990.marker{id: 1362} + <251:-1>*0x1793b370.marker{id: 1440} + <251:1>*0x17942760.marker{id: 1360} + <251:1>*0x17982470.marker{id: 1393} + <251:1>*0x17984f90.marker{id: 1391} + <251:1>*0x1798d750.marker{id: 1422} + <251:-1>*0x17991340.marker{id: 1409} + <251:-1>*0x179919d0.marker{id: 1415} + <750:-3.29688e-08>*UIView:0x165c9b50.Width{id: 1841} + <750:5.4948e-08>*UIView:0x1797bdc0.Width{id: 1858} + <999:1>*_UILayoutGuide:0x16549bf0.Width{id: 4} + <999:1>*_UILayoutGuide:0x1654a260.Width{id: 7} + <999:1>*_UILayoutGuide:0x1658ccf0.Width{id: 80} + <999:1>*_UILayoutGuide:0x1658ced0.Width{id: 83}}`

it occurs in line 413 of MMDrawerController:

`[oldCenterViewController.view removeFromSuperview];`

any help would be very much appreciated :D

**Comment by bjarkehs** [comment]
Did you check that you are actually using the newest version? Line 413 does not contain anything about `removeFromSuperview` in the two latest releases.
