### ISSUE TITLE
How can I tell when a drawer did open, programatically?

### ISSUE THREAD

**Issue by nsaronson** [mutualmobile/MMDrawerController#447]
I would like to enable (become first responder) a text field when my right drawer opens.

**Comment by thomasbaldwin** [comment]
Looking for something similar. Did you ever find a solution @nathanandersen ?

**Comment by nsaronson** [comment]
I have not found a solution, since I looked at the low src and didn't want to override the gesture handler.

What I did instead, was rather implemented a basic pan gesture on the Central controller that handled opening to the desired side, and in that method I called `mm_drawercontroller.open...` (or whatever it is from the documentation), and then did my custom handling.

It does lose the nice functionality of the preview by peeking, but, it does do my custom handling, so pick your poison.

**Comment by andreyrd** [comment]
If you subclass MMDrawerController, there is a method you can override to get notified when a drawer opens. Don't forget to call super!

`func prepareToPresentDrawer(drawer: MMDrawerSide, animated: Bool)`

This will be called whenever either the left or the right drawer _begins_ opening. Unfortunately, it isn't called when the center drawer is about to come back, which is what I was looking for when I found it. :P

**Comment by altagir** [comment]
doesn't onViewWillAppear respond for left and right panels?
