### ISSUE TITLE
Side viewcontroller behind status bar

### ISSUE THREAD

**Issue by iSalah** [mutualmobile/MMDrawerController#451]
Hi,

The side viewController appears behind the iOS status bar when it is loaded from a storyboard.

Steps to reproduce the issue:
1. Load kitchensink example project
2. Set a custom viewController instantiated from storyboard as a side viewController

`UIStoryboard *storyboard = [UIStoryboard storyboardWithName:@"Right" bundle: nil]; 
 UIViewController *rightSideDrawerViewController = [storyboard instantiateViewControllerWithIdentifier:@"right"];
`
3. Run project, open right side viewController: the viewController is behind the statusBar
4. Press home button, open the app again: the viewController automatically moves below the statusBar 

How to prevent this behavior ?
Thanks

**Comment by iSalah** [comment]
Here is the GIF to illustrate the issue:

![ezgif com-gif-maker 1](https://cloud.githubusercontent.com/assets/349272/15355362/6f32b0ac-1cf2-11e6-9207-0df5785bf122.gif)

**Comment by nfidevstudio** [comment]
Hi, i solved the problem configuring the top constraint of view to **Superview.Top** instead of **Top Layout Guide .Bottom**

**Comment by iSalah** [comment]
Great, it solved my issue !
Thank you @nfidevstudio
