### ISSUE TITLE
iOS 10 beta crash initWithCenterViewController:leftDrawerViewController:rightDrawerViewController

### ISSUE THREAD

**Issue by simplatek** [mutualmobile/MMDrawerController#457]
running iOS 10 beta, our app is now crashing during initialization of drawers using just left and center drawer view controllers, crashes at addViewController with following exception:

child view controller:[MyViewController] should have parent view controller:[UINavigationController] but requested parent is [MMDrawerController]

**Comment by altagir** [comment]
Your initialisation code would be helpful
I saw no issue with ios10 beta. 
You probably pass wrong parameters

**Comment by simplatek** [comment]
my bad, this was a bug on my end as I reinitialized the drawerController with existing viewController, it works in iOS 10 beta thx!
