### ISSUE TITLE
Disable open drawer

### ISSUE THREAD

**Issue by astrokin** [mutualmobile/MMDrawerController#463]
Is there any way to disable open drawer for some of the view controllers in navigation stack of `centerViewController`?

I've tried
`drawer.openDrawerGestureModeMask = .Custom`
and

``` swift
drawer.setGestureShouldRecognizeTouchBlock { (drawer, recognizer, touch) -> Bool in
                if mycondition {
                    return false
                }
                return true
            }
```

but it seems that MMDrawerController intercept all touches then, and if UITableView inside `centerViewController` it's selection stops work.

**Comment by astrokin** [comment]
actually i was able to find a solution by my own.

``` swift
// MARK: - Drawer
extension UIViewController {

    func disableSideMenuOpening() {
        if mm_drawerController != nil {
            mm_drawerController.openDrawerGestureModeMask = .None
        }
    }

    func enableSideMenuOpening() {
        if mm_drawerController != nil {
            mm_drawerController.openDrawerGestureModeMask = .All
        }
    }
}
```

**Comment by yannbu** [comment]
Hi,

Did you migrate to swift 3 ? 

`mm_drawerController.openDrawerGestureModeMask = .None` doesn't work anymore in swift 3 

please see #470
