### ISSUE TITLE
Missing Navigation Bar

### ISSUE THREAD

**Issue by cchamnab** [mutualmobile/MMDrawerController#471]
In my center view controller, I have added Navigation Controller to show Navigation Bar. After I added MMDrawerController , the Navigation Bar don't show anymore.

<code>
- (BOOL)application:(UIApplication *)application willFinishLaunchingWithOptions:(NSDictionary *)launchOptions{
    
    ViewController *mainVC = [[UIStoryboard storyboardWithName:@"Main" bundle:nil] instantiateViewControllerWithIdentifier:@"idMain"];
    
    DrawerViewController *drawerVC = [[UIStoryboard storyboardWithName:@"Main" bundle:nil] instantiateViewControllerWithIdentifier:@"idDrawer"];
    
    self.drawerController = [[MMDrawerController alloc] initWithCenterViewController:mainVC leftDrawerViewController:drawerVC];
    
    [self.drawerController setOpenDrawerGestureModeMask:MMOpenDrawerGestureModeAll];
    [self.drawerController setCloseDrawerGestureModeMask:MMCloseDrawerGestureModeAll];
    
    [self.window setRootViewController:self.drawerController];
    
    return YES;
}
</code>

**Comment by altagir** [comment]
mainVC seems to be UIViewController class, not UINavigationController
Does mainId refers to the nav or the embedded view controller?

**Comment by cchamnab** [comment]
idMain is refer to UIViewController. Should I instantiate from UINavigationController that embedded UIViewController ?

**Comment by altagir** [comment]
Definitely :)
