### ISSUE TITLE
Undefined symbols for architecture x86_64

### ISSUE THREAD

**Issue by cchamnab** [mutualmobile/MMDrawerController#472]
Below It is my code : 

`HomeNavigationController *mainVC = [[UIStoryboard storyboardWithName:@"Main" bundle:nil] instantiateViewControllerWithIdentifier:@"idMainNav"];
    
    DrawerViewController *drawerVC = [[UIStoryboard storyboardWithName:@"Main" bundle:nil] instantiateViewControllerWithIdentifier:@"idDrawer"];
    
    self.drawerController = [[MMDrawerController alloc] initWithCenterViewController:mainVC leftDrawerViewController:drawerVC];
    [self.drawerController setShowsShadow:YES];
    [self.drawerController setOpenDrawerGestureModeMask:MMOpenDrawerGestureModeAll];
    [self.drawerController setCloseDrawerGestureModeMask:MMCloseDrawerGestureModeAll];
    
    [self.window setRootViewController:self.drawerController];
`

When i'm building the app, I've got following error : 

> Undefined symbols for architecture x86_64:
  "_OBJC_CLASS_$_MMDrawerController", referenced from:
      objc-class-ref in AppDelegate.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by altagir** [comment]
did you include the pod correctly and opened the workspace ?

**Comment by cchamnab** [comment]
I imported code manually So I think problem because of that.
