### ISSUE TITLE
Hide keyboard when opening drawer?

### ISSUE THREAD

**Issue by stefanhenze** [mutualmobile/MMDrawerController#64]
I have a text input in my center view. I'd like to hide the keyboard when the drawer is opened. Is there a delegate method that is called when the drawer is opened to resign first responder or another way to achieve this?

**Comment by onmyway133** [comment]
@kcharwood the `drawerVisualStateBlock` is called in `UIGestureRecognizerStateChanged`, after `self.view.userInteractionEnabled = NO` so it is late. It does not work

Here is my code

```
[self setDrawerVisualStateBlock:^(MMDrawerController *drawerController, MMDrawerSide drawerSide, CGFloat percentVisible) {
        [[UIApplication sharedApplication] sendAction:@selector(resignFirstResponder) to:nil from:nil forEvent:nil];
    }];
```
