### ISSUE TITLE
How do I push from the center viewcontroller?

### ISSUE THREAD

**Issue by kkendall33** [mutualmobile/MMDrawerController#90]
Sorry to bug, again...  I want to push from the center viewcontroller.  When I do (one of) the following, I can't swipe to view the left side view, when I normally can.

[AppDelegate.navigationController pushViewController:aVC animated:YES];
[AppDelegate.drawerController.navigationController pushViewController:aVC animated:YES];
[AppDelegate.drawerController.centerViewController.navigationController pushViewController:aVC animated:YES];

This is how I have things setup in my app delegate:

self.drawerController = [[MMDrawerController alloc]
                             initWithCenterViewController:centerViewController
                             leftDrawerViewController:leftSideDrawerViewController
                             rightDrawerViewController:nil];

self.navigationController = [[UINavigationController alloc] initWithRootViewController:self.drawerController];

Thank you for the help!!!

**Comment by GopalPatel1989** [comment]
I want to push a view controller from MMDrawerController, in drawer i've used table view and didselect method is used to navigate to other controller but it doesn't showing navigation bar in that controller please help me. Here is the code I tried in didselect method:

```
if (self.currentIndex == indexPath.row) {
    [self.mm_drawerController closeDrawerAnimated:YES completion:nil];
    return;   
}
UIStoryboard *mainStoryboard = [UIStoryboard storyboardWithName:@"Main"
                                                         bundle: nil];
UIViewController *vc ;
vc.navigationController.navigationBarHidden = FALSE;
vc = [mainStoryboard instantiateViewControllerWithIdentifier: @"AlbumVC"];

if (vc) {
    self.currentIndex = indexPath.row;
    [self.mm_drawerController setCenterViewController:vc withCloseAnimation:YES completion:nil];    
} else {
    [self.mm_drawerController closeDrawerAnimated:YES completion:nil];
}
```

**Comment by altagir** [comment]
right now you are pushing a view without navigation controller, so no nav bar...
you need to push a navigation controller whose root view controller is your view controller.

so In your storyboard, rename your actual view Controller id "MainContent" and add a navigation controller whose Id is named Main, and which rootController is your viewController "mainContent"

```
SWLNavigationController* viewNavCtrl = [mainStoryboard instantiateViewControllerWithIdentifier:@"Main"];    
if (viewNavCtrl)
 [self.mm_drawerController setCenterViewController:viewNavCtrl withCloseAnimation:YES completion:nil];
...
```
